### ISSUE TITLE
[Question] Creating MIME messages with attachments

### ISSUE THREAD

**Issue by pdgonzalez872** [terceiro/rmail#8]
I have a question about the api your gem provides. I'm using your gem in conjunction with [`google-api-client`](https://github.com/google/google-api-ruby-client) and was wondering how to add attachments to the `RMail::Message` object.

I'm following the sample in the google gem's repo, [here](https://github.com/google/google-api-ruby-client/blob/master/samples/cli/lib/samples/gmail.rb#L62-L75).

Thank you!

**Comment by terceiro** [comment]
Hi, sorry but I'm not able to produce a comprehensive answer at the moment. You can check how [feed2imap](/feed2imap/feed2imap) uses the API. See in special [lib/feed2imap/itemtomail.rb](https://github.com/feed2imap/feed2imap/blob/master/lib/feed2imap/itemtomail.rb#L82-L127)

**Comment by ejstembler** [comment]
@pdgonzalez872, @terceiro I had to do this recently and got it working.  Here's a function I wrote:

```ruby
def create_message_with_attachment(to, from, subject, body, filename)
  progname = 'GmailMailer::create_message_with_attachment'
  begin
    # Create the attachment part
    attachment_part = RMail::Message.new
    attachment_part.header.set('Content-Disposition', 'attachment', 'filename' => File.basename(filename))
    attachment_part.body = File.read(filename)
    # Create the text part
    text_part = RMail::Message.new
    text_part.body = body
    # Create the message
    message = RMail::Message.new
    message.header['To'] = to
    message.header['From'] = from
    message.header['Subject'] = subject
    message.body = [text_part, attachment_part]
    message
  rescue => ex
    @logger.error(progname) { ex.message }
    raise ex
  end
end
```

Usage:

```ruby
def send_message!(message, user_id='me')
  progname = 'GmailMailer::send_message!'
  # Pre-conditions
  fail RuntimeError, 'message is nil' unless message
  begin
    service.send_user_message(user_id, upload_source: StringIO.new(message.to_s), content_type: 'message/rfc822')
  rescue Google::Apis::Error => ex
    @logger.debug(progname) { "status_code=#{ex.status_code}, body=\n\n#{ex.body}" }
    @logger.error(progname) { ex.message }
    raise ex
  rescue => ex
    @logger.error(progname) { ex.message }
    raise ex
  end
end
```

**Comment by pdgonzalez872** [comment]
Thanks for this @ejstembler ! I'm going to go ahead and close this issue though. Thanks again!
